### ISSUE TITLE
Error in fluentd daemonsets "Failed to open TCP connection to sts.us-east-1.amazonaws.com:443 (getaddrinfo: No such host is known. )"

### ISSUE THREAD

**Issue by KiranmaiKalla** [bgsilvait/k8s-fluentd-windows#1]
Getting below error in fluentd daemonsets,
2021-03-01 22:04:40 +0000 [error]: #0 unexpected error error_class=Seahorse::Client::NetworkingError error="Failed to open TCP connection to sts.us-east-1.amazonaws.com:443 (getaddrinfo: No such host is known. )"

**Comment by bgsilvait** [comment]
The issue seems to be related to the fluentd pod can't reach sts endpoint. Sts endpoint is used to get IAM credentials using IRSA to pod be able to interact with CW APi.

Check if your VPC has vpc endpoints for sts(and if the SG allow 443 from EKS nodes). Try to test with another pod using the same service account and run  $ aws sts get-caller-identity
